# Generated by Django 4.2.8 on 2023-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WireData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('level', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
